// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Usuarios.Data;

#nullable disable

namespace apisv.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Usuarios.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("usuario_cpf");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("usuario_login");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("usuario_senha");

                    b.Property<string>("data_nascimento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("usuario_data_nascimento");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("usuario_nome");

                    b.Property<string>("usuarioURL")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("usuario_url");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "111.222.333-44",
                            Login = "usuario1",
                            Senha = "senha123",
                            data_nascimento = "1990-01-15",
                            nome = "Fulano da Silva",
                            usuarioURL = ""
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "222.333.444-55",
                            Login = "usuario2",
                            Senha = "senha456",
                            data_nascimento = "1985-05-20",
                            nome = "Beltrano Oliveira",
                            usuarioURL = ""
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "333.444.555-66",
                            Login = "usuario3",
                            Senha = "senha789",
                            data_nascimento = "1988-10-10",
                            nome = "Ciclano Pereira",
                            usuarioURL = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
